//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Salon
{
    using System;
    using System.Collections.Generic;
    
    public partial class Portfolio
    {
        public int MasterId { get; set; }
        public int WorkId { get; set; }
        public string Name { get; set; }
        public byte[] Image { get; set; }
    
        public virtual User User { get; set; }
    }
}
