//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Salon
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public int ClientId { get; set; }
        public int MasterId { get; set; }
        public System.DateTime Date_and_time { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual User User { get; set; }
    }
}
